#!/bin/bash
set -e

BAM_DB_NAME=${BAM_DB_NAME:-bamdata}
BAM_DB_USER=${BAM_DB_USER:-bam}
BAM_DB_PWD=${BAM_DB_PWD:-password}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${BAM_DB_USER} WITH PASSWORD '${BAM_DB_PWD}';
    CREATE DATABASE ${BAM_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${BAM_DB_NAME} TO ${BAM_DB_USER};
EOSQL

